/* Content thats used for the BannersDesign.js file */

/* ID Lab Content */
const idLabBannerHtml=`
<main id="main">

<section id="about" class="fade-scroll">
  <div class="container-fluid">
    <div class="about-container">
      <div id="particles-js" class="row w-100 h-100 animated fadeIn"></div>
      <div class="row">
        <div id="welcome-heading" class="col-lg-8">
          <div id="lab-name">DEPAUL INNOVATION DEVELOPMENT LAB</div>
          <div class="txt-xl">We Bring Innovative Ideas to Life</div>
          <div class="welcome-text txt-rg">
            We partner and collaborate with our clients to provide excellent service on turning innovative ideas into functional and testable prototypes at a quick turnaround.
          </div>
<!--              <a id="btn-welcome" href="#" class="btn no-radius uppercase">Learn more-->
<!--                <span class="la la-arrow-right left-sapce"></span>-->
<!--              </a>-->
        </div>
      </div>
      <div class="row">
        <div id="bottom-arrow" class="col-md-12 text-center">
          <div id="button-arrow">
            <a href="#strategies"><i class="la la-arrow-down la-2x"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="strategies" class="h-100">
  <div class="container-fluid">
    <div id="strategies-content-1" class="row fade-scroll">
      <div id="strategies-text" class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
        <div class="txt-lg text-light strategies-title">Our Mission</div>
        <div class="txt-rg text-light strategies-description justify-content-md-center">We partner and collaborate with our clients to provide excellent service on turning innovative ideas into functional and testable prototypes at a quick turnaround.</div>
        <br>
        <div class="txt-lg text-light strategies-title">Our Vision</div>
        <div class="txt-rg text-light strategies-description justify-content-md-center">We envision growing into a leading technology innovation hub in the city of Chicago through partnership with top companies from diverse industries, and to create and develop industry-focused, user-centric innovative ideas that will adapt to the needs of a rapidly changing world.</div>
<!--            <a id="btn-case-studies-2" href="#" class="btn-case-studies btn no-border btn-arrow txt-btn">See case studies <span class="la la-arrow-right left-space"></span></a>-->
      </div>
      <div class="col-xs-12 colsm-12 col-md-12 col-lg-6 col-xl-6 strategies-image-div">
        <img id="strategies-image-1" class="strategies-image" src="wp-content/themes/idlabtheme/img/hero-section.jpg">
      </div>
    </div>
  </div>
</section>

<section id="foundation">
  <div class="container-fluid">
    <div class="col-12">
      <div id="foundation-yele" class="row justify-content-end">
        <div id="foundation-pic" class="col-xs-12 col-sm-12 col-md-5 col-lg-5 col-xl-5">
          <div id="foundation-imagebox" class="d-flex justify-content-md-center justify-content-lg-start justify-content-xl-start">
            <img src="wp-content/themes/idlabtheme/img/new-foundation-yele.jpg">
          </div>
        </div>
        <div id="foundation-text" class="col-xs-12 col-sm-12 col-md-12 col-lg-7 col-xl-7 px-lg-1">
          <div id="foundation-title" class="d-flex flex-row align-items-center txt-lg">
            <div>How We Started</div>
            <div class="divider"><div class="inner"></div></div>
          </div>
          <div id="foundation-description" class="txt-rg text-justify">
            DePaul’s ID Lab was founded by Dr. Olayele Adelakun based on his research on Information Technology innovation and outsourcing which led to the development of re-defining the University – Corporate relationship. The ID Lab was born and designed to grow into a leading innovation hub in Chicago through a partnership between the University and top companies in the industry through top development, design and data analytics.
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="our-thinking">
  <div class="container-fluid">
    <div class="row">
      <div id="our-thinking-title" class="d-flex flex-row align-items-center txt-lg">
        <div>Our thinking</div>
        <div class="divider"><div class="inner"></div></div>
      </div>
    </div>
    <div id="our-thinking-background"class="row">
      <div id="our-thinking-box"></div>
      <div id="our-thinking-1" class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <h2 class="txt-md">Collaboration is at the Center of Our Core</h2>
        <div id="our-thinking-1-description" class="txt-rg text-justify">
          We take on your complex challenge and look at the big question to develop your innovative idea and
          create a user-centric solution that will grow your business and create meaningful relationships with
          your users. We ensure having a functional prototype at a quick turnaround using the agile methodology.
        </div>
      </div>
      <div id="our-thinking-2" class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <h2 class="txt-lg">What’s Agile?</h2>
        <div id="our-thinking-2-description" class="txt-rg text-justify">
          A method that values individuals, interactions and progress. We   collaborate closely with our customers
          so that we can respond to change in real time from direct feedback and deliver changes at a fast pace.
          We use  University research resources such as the usability lab and 3D printing to deliver the best
          results to you.
        </div>
      </div>
    </div>
  </div>
</section>

<section id="our-clients" > <!--class="fade-scroll"-->
  <div class="container-fluid">
    <div id="our-clients-content" class="row justify-content-center">
      <div id="our-clients-title" class="col-12 txt-lg text-center">Our clients</div>
      <div id="our-clients-list" class="row justify-content-center align-items-center col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xl-12">
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/abbott.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/career-builder.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/allstate.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/bosch.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client cdw-logo">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/cdw.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/digitalmint.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/continental.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/kimberly.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/baxter.png" class="w-100 h-100">
          </a>
        </div>
        <div class="our-clients-client legalGeneral-logo">
          <a>
            <img src="wp-content/themes/idlabtheme/img/clients/legal_general.png" class="w-100 h-100">
          </a>
        </div>
      </div>
    </div>
    </div>
  </section>

<section id="leadership" class="col-12">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div id="leadership-heading" class="row justify-content-center col-xs-12 col-sm-12 col-md-9 col-lg-7 col-xl-6">
        <div id="leadership-title" class="txt-lg">Leadership</div>
<!--              <div id="leadership-text" class="txt-rg text-center">-->
<!--                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's Lorem Ipsum is simply Lorem -->
<!--              </div>-->
      </div>
    </div>
    <div class="leadership-group row justify-content-center">
      <div class="row justify-content-center col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-9">
        <div class="leadership-item col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
          <a href="https://www.linkedin.com/in/patrickemmons/" class="just-link" target="_blank">
          <img src="wp-content/themes/idlabtheme/img/board/patrick.jpg">
          <div class="board-name px-3 pt-4">Patrick Emmons</div>
          <div class="board-title px-3 pb-4">CEO <br><br> DragonSpears</div>
          </a>
        </div>
        <div class="leadership-item col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
          <a href="https://www.linkedin.com/in/nickionita/" class="just-link" target="_blank">
          <img src="wp-content/themes/idlabtheme/img/board/nick.jpg">
          <div class="board-name px-3 pt-4">Nick Ionita</div>
          <div class="board-title px-3 pb-4">Co-Founder/CEO <br><br> Flux</div>
          </a>
        </div>
        <div class="leadership-item col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
          <a href="https://www.linkedin.com/in/lawrenceedwardjohnson/" class="just-link" target="_blank">
          <img src="wp-content/themes/idlabtheme/img/board/lawrence.JPG">
          <div class="board-name px-3 pt-4">Lawrence Johnson</div>
          <div class="board-title px-3 pb-4">
            SVP and Head of Fintech Engagement <br><br> Morningstar
          </div>
          </a>
        </div>
        <div class="leadership-item col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
          <a href="https://www.linkedin.com/in/ram-jambunathan-350667/" class="just-link" target="_blank">
          <img src="wp-content/themes/idlabtheme/img/board/ram.jpg">
          <div class="board-name px-3 pt-4">Ram Jambunathan</div>
          <div class="board-title px-3 pb-4">SVP and Managing Director <br><br> SAP</div>
          </a>
        </div>
        <div class="leadership-item col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
          <a href="https://www.linkedin.com/in/lauren-rosen-growth-strategy/" class="just-link" target="_blank">
          <img src="wp-content/themes/idlabtheme/img/board/lauren.jpg">
          <div class="board-name px-3 pt-4">Lauren Rosen</div>
          <div class="board-title px-3 pb-4">Innovation Partner - Office of Innovation <br><br> Salesforce</div>
          </a>
        </div>
        <div class="leadership-item col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-3">
          <a href="https://www.linkedin.com/in/dwayne-prosko-a1350/" class="just-link" target="_blank">
            <img src="wp-content/themes/idlabtheme/img/board/dwayneProsko.jpg">
            <div class="board-name px-3 pt-4">Dwayne Prosko</div>
            <div class="board-title px-3 pb-4">Managing Director <br><br> KPMG</div>
          </a>
        </div>

      </div>
    </div>
  </div>
</section>

<section id="business">
  <div class="container-fluid">
    <div class="row row-eq-height">
      <div class="business-container d-flex col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <div id="business-left" class="business-box col-12">
          <div id="business-left-title" class="business-title btm-box-title">Strategic Partnership</div>
          <div id="business-left-text" class="business-text btm-box-text">
            Looking for help to expand your innovative portfolio and add value to your business? Let us become
            your strategic partner and grow your business by using our expertise in data analytics, software
            development and UI/UX design.
          </div>
          <a id="business-left-btn" href="../contact-us" class="btn btn-business no-radius btn-arrow txt-box-btn">Get Involved<span class="la la-arrow-right left-sapce"></span></a>
        </div>
      </div>
      <div class="business-container d-flex col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <div id="business-right" class="business-box col-12">
          <div id="business-right-title" class="business-title btm-box-title">Business Inquiry</div>
          <div id="business-right-text" class="business-text btm-box-text">
            Want to learn more about us, or need help with a problem, or developing a specific solution?  Get in
            touch with us to learn our capabilities and what we can do for your business.
          </div>
          <a id="business-right-btn" href="../contact-us" class="btn btn-business no-radius btn-arrow txt-box-btn">Contact Us<span class="la la-arrow-right left-sapce"></span></a>
        </div>
      </div>
    </div>
    </div>
  </section>

</main>
`;

const idLabBannerCss=`
/*----------------------------------------------------------------------------------------------------------------------
--------------------------------------------------- HEADER -------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------*/

#header {
  padding: 15px 0;
  position: fixed;
  left: 0;
  top: 0;
  right: 0;
  transition: all 0.5s;
  z-index: 997;
  background: white;
}
#header #logo {
  float: left;
  padding-left: 55px;
}
#header #logo img {
  width: 55px;
  height: 58px;
}
#header #logo h1 {
  font-size: 36px;
  margin: 0;
  padding: 6px 0;
  line-height: 1;
  font-family: "Poppins", sans-serif;
  font-weight: 700;
  letter-spacing: 3px;
  text-transform: uppercase;
}
#header #logo h1 a, #header #logo h1 a:hover {
  color: #fff;
}
#header #logo img {
  padding: 0;
  margin: 0;
}
#header.header-fixed {
  background: rgba(255,255,255, 0.9);
  padding: 15px 0;
  transition: all 0.5s;
}

@media (max-width: 768px) {
  #header #logo h1 {
    font-size: 26px;
  }
  #header #logo img {
    max-height: 40px;
  }
  #header #logo {
    padding-left: 0;
  }
}

/* ------- HERO ------- */
#hero {
  width: 100%;
  height: 100vh;
  background: url(wp-content/themes/idlabtheme/img/hero-bg.jpg) top center;
  background-size: cover;
  position: relative;
}
#hero:before {
  content: "";
  background: rgba(0, 0, 0, 0.6);
  position: absolute;
  bottom: 0;
  top: 0;
  left: 0;
  right: 0;
}
#hero .hero-container {
  position: absolute;
  bottom: 0;
  top: 0;
  left: 0;
  right: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  text-align: center;
}
#hero h1 {
  margin: 30px 0 10px 0;
  font-size: 48px;
  font-weight: 700;
  line-height: 56px;
  text-transform: uppercase;
  color: #fff;
}
#hero h2 {
  color: #eee;
  margin-bottom: 50px;
  font-size: 24px;
}
#hero .btn-get-started {
  font-family: "Poppins", sans-serif;
  text-transform: uppercase;
  font-weight: 500;
  font-size: 16px;
  letter-spacing: 1px;
  display: inline-block;
  padding: 8px 28px;
  border-radius: 50px;
  transition: 0.5s;
  margin: 10px;
  border: 2px solid #fff;
  color: #fff;
}
#hero .btn-get-started:hover {
  background: #2dc997;
  border: 2px solid #2dc997;
}

@media (min-width: 1025px) {
  #hero {
    background-attachment: fixed;
  }
  .btn-business span {
    top: 35%;
  }
}
@media (max-width: 768px) {
  #hero h1 {
    font-size: 28px;
    line-height: 36px;
  }
  #hero h2 {
    font-size: 18px;
    line-height: 24px;
    margin-bottom: 30px;
  }
}

`;

/* ODI Content */
const odiBannerHtml=`
<!-- Home-->
<header class="masthead" id="home">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-center">
                <h1 class="text-capitalize text-white font-weight-light letter-spacer pt-7 header-text">Optimize Digital Innovation:</h1>
                <h1 class="sub-text text-left text-white font-weight-bold letter-spacer header-text2">For a Great Reset</h1>
            </div>

            <div class="col-lg-10 align-self-start pad-more">
                <div class="hero-img-div justify-content-left text-left">
                    <img src="assets/img/HighLight.svg" width="49px" height="81px">
                </div>
                <div class="hero-detail-div justify-content-left text-left">
                    <p class="text-white font-weight-light mb-3 hero-detail-para sub-text">October 15th-16th, 2020</p>
                    <p class="text-white font-weight-light sub-text">DePaul University, Chicago, IL</p>
                </div>
            </div>

            <div class="col-lg-10 align-self-start pad-more">
                <div class="justify-content-left text-left pad-more header-button d-flex">
                  <!-- <a class="btn btn-secondary btn-xl text-uppercase resp-button disabled" href="#">Registeration Comming Soon</a> -->
                  <a target="_blank" class="btn btn-outline-blue btn-xl text-uppercase resp-button" href="https://my.cdm.depaul.edu/CIM/ODIConf/register">Register Here</a>
                  <a class="btn btn-danger btn-xl text-uppercase resp-button mx-3" href="#">Join Conference</a>
                </div>

                  <!--Modal-->
                  <div class="modal modal-open" id="registrationModal" tabindex="-1" role="dialog">
                      <div class="modal-dialog modal-show" role="document">
                          <div class="modal-content">
                              <div class="modal-header">
                                  <div> <img  class="modal-image" width="115px" src="./assets/img/Group 103.svg"/></div>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                  </button>
                              </div>
                              <div class="modal-body justify-content-center">
                                  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdFv8p-eUgvvTK21U-tCkgsVmcrzpcTZe2brfRY3mdkoKO-Jw/viewform?embedded=true" width="100%" height="750" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
                              </div>
                              <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              </div>
                          </div>
                      </div>
                  </div>


                  <!--Modal-->
                  <div class="modal modal-open" id="codeModal" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-show" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <div> <img  class="modal-image" width="115px" src="./assets/img/Group 103.svg"/></div>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body justify-content-center">
                              <p id ="error-message" style="color: red; display: none;">Registration code is incorrect, please try again.</p>
                              <p>Enter your registration code: </p>
                              <div>
                                <form name="registrationCode">
                                  <input class="justify-content-center" type="password" name="inputCode"/>

                                  <div class="regSubmit modal-button">
                                    <input type="button" class="btn btn-secondary btn-xl text-uppercase" onclick="check(this.form)" value="Submit"/>

                                  </div>
                                </form>

                              </div>

                            </div>
                            <div class="modal-footer">
                                <p class="text-left"><a class="text-left noRegCode" >Payment Registration Coming Soon!</a></p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="justify-content-center align-self-baseline hero-arrow-div">
                <a class="btn js-scroll-trigger" href="#about"><img src="assets/img/Arrow%20Button.svg"></a>
            </div>

        </div>
    </div>
</header>
`;

const odiBannerCss=`
article, aside, figcaption, figure, footer, header, hgroup, main, nav, section {
    display: block;
  }
  .modal-dialog-scrollable .modal-header,
.modal-dialog-scrollable .modal-footer {
  flex-shrink: 0;
}
.modal-header {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    padding: 1rem 1rem;
    border-bottom: 1px solid #dee2e6;
    border-top-left-radius: calc(0.3rem - 1px);
    border-top-right-radius: calc(0.3rem - 1px);
  }
  .modal-header .close {
    padding: 1rem 1rem;
    margin: -1rem -1rem -1rem auto;
  }
  .header-text{
    margin-top: 1rem !important;
    margin-bottom: 2rem !important;
    font-size: 1.0rem !important;
    padding-left: 1.2rem !important;
    letter-spacing: 0.2rem !important;
    padding-top: 0rem !important;
    text-align: left !important;
  }
  .header-text2{
    margin-top: 1rem !important;
    margin-bottom: 2rem !important;
    font-size: 1.8rem !important;
    padding-left: 1.2rem !important;
    letter-spacing: 0.3rem !important;
  }
  .header-button{
    margin-top: 9rem !important;
    float: none !important;
    justify-content: center !important;
    text-align: center !important;
  }
  @media (max-width: 1025px){
    .header-text{
      padding-left: 0.7rem !important;
      text-align: left;
    }
    .header-text2{
     padding-left: 1rem !important;
     }
   }
   header.masthead {
    padding-top: 10rem;
    padding-bottom: calc(10rem - 4.5rem);
    background: linear-gradient(to bottom, rgba(0, 26, 44, 0.8) 0%, rgba(0, 26, 44, 0.8) 100%), url("../assets/img/img_5599_32251013438_o-min.jpg");
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: scroll;
    background-size: cover;
  }
  header.masthead h1 {
    font-size: 2.25rem;
  }
  @media (min-width: 992px) {
    header.masthead {
      height: 100vh;
      min-height: 40rem;
      padding-top: 4.5rem;
      padding-bottom: 0;
    }
    header.masthead p {
      font-size: 1.5rem;
    }
    header.masthead h1 {
      font-size: 2.4rem;
    }
  }
  @media (min-width: 1200px) {
    header.masthead h1 {
      font-size: 3.5rem;
    }
  }
`;



/* Knowledge Portal */

const ikpBannerHtml=`
<div class="fl-row-content-wrap">
						<div class="fl-row-content fl-row-full-width fl-node-content">
		
<div class="fl-col-group fl-node-5e960343743e9" data-node="5e960343743e9">
			<div class="fl-col fl-node-5e960343743ed" data-node="5e960343743ed">
	<div class="fl-col-content fl-node-content">
	<div class="fl-module fl-module-rich-text fl-node-5ed5e8dc0f1e2" data-node="5ed5e8dc0f1e2">
	<div class="fl-module-content fl-node-content">
		<div class="fl-rich-text">
	<h3 style="text-align: center;"><strong>iD Lab</strong></h3>
<h3 style="text-align: center;"><strong>I</strong>nnovation <strong>K</strong>nowledge <strong>P</strong>ortal</h3>
</div>
	</div>
</div>
	</div>
</div>
	</div>
		</div>
	</div>

`;

const ikpBannerCss=`
 Cannot retrieve the CSS
`;



export const banners=[idLabBannerHtml,idLabBannerCss,odiBannerHtml,odiBannerCss,ikpBannerHtml,ikpBannerCss];